import { Button } from '@mui/material';
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>

      <main className="app">
        <div className="w-full h-screen flex flex-col items-center justify-start">
          <Button color="primary" variant="contained">Hello World</Button>
        </div>
      </main>
    </div>
  );
}

export default Home
